In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from uncertainties import ufloat
from uncertainties import unumpy as unp
from uncertainties.umath import sqrt

In [3]:
df = pd.read_excel("data/OPA.xlsx", sheet_name = "A4")
df_a = df.iloc[0:5, 0:3]
df_b = df.iloc[15:20, 0:3]
df_a.columns = ["Messung", "Pos E", "Pos G"]
df_b.columns = ["Messung", "Links", "Rechts"]
df_b

   Messung Links Rechts
15       1  46.8     75
16       2    47   75.2
17       3  46.8   75.3
18       4  46.9   75.2
19       5  46.9   74.9

In [8]:
# auto dings da
u_x = 0.1 # cm

pos_schirm = ufloat(39.0, u_x)
pos_linse_autokol = ufloat(53.0, u_x)

# WICHTIG: u_x auch bei "Pos G" hinzufügen
df_a["k"] = unp.uarray(df_a["Pos E"], u_x) - pos_schirm
df_a["l"] = pos_linse_autokol - unp.uarray(df_a["Pos G"], u_x)

k_final = sum(df_a["k"]) / len(df_a["k"])
l_final = sum(df_a["l"]) / len(df_a["l"])

# 2. Bessel
e = ufloat(100.0, u_x) - ufloat(33.0, u_x)
df_b["d"] = unp.uarray(df_b.Rechts, u_x) - unp.uarray(df_b.Links, u_x)
d_avg = sum(df_b["d"]) / len(df_b["d"])

In [9]:
df_b

   Messung Links Rechts             d
15       1  46.8     75  28.20+/-0.14
16       2    47   75.2  28.20+/-0.14
17       3  46.8   75.3  28.50+/-0.14
18       4  46.9   75.2  28.30+/-0.14
19       5  46.9   74.9  28.00+/-0.14

In [10]:
term = sqrt((e - k_final - l_final)**2 - d_avg**2)

f_prime = 0.5 * term
h = (k_final + l_final) - term

print(f"Avg k: {k_final:.2uP} cm")
print(f"Avg l: {l_final:.2uP} cm")
print(f"Avg d: {d_avg:.2uP} cm")
print(f"Avg e: {e:.2uP} cm")
print("-" * 30)
print(f"Brennweite f':          {f_prime:.2uP} cm")
print(f"Hauptebenenabstand h:   {h:.2uP} cm")

Avg k: 8.66±0.11 cm
Avg l: 19.50±0.11 cm
Avg d: 28.240±0.063 cm
Avg e: 67.00±0.14 cm
------------------------------
Brennweite f':          13.33±0.16 cm
Hauptebenenabstand h:   1.49±0.44 cm